apiVersion: v1
kind: Service
metadata:
  name: storesc-sqlserver-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: storesc-sqlserver
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

  