version: '3.4'
services:
  database:
    build: ./environment/database
    environment:
      SA_PASSWORD: "Stor3sc@2023"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  api:
    build: ./
    ports:
      - "8081:80"
