apiVersion: v1
kind: Service
metadata:
  name: storesc-load-balancer
  labels:
    app: storesc-api
  namespace: storesc
spec:
  type: LoadBalancer
  ports:
  - name: storesc-load-balancer
    port: 80
    targetPort: 80
  selector:
    app: storesc-api