apiVersion: apps/v1
kind: Deployment
metadata:
  name: storesc-deployment
  namespace: storesc
  labels:
    app: storesc-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: storesc-api
  template:
    metadata:
      labels:
        app: storesc-api
    spec:
      containers:
      - name: storesc-api-pod
        image: storesc/storesc-api:latest #minikube image load <IMAGE:TAG>
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
