apiVersion: apps/v1
kind: Deployment
metadata:
  name: storesc-api
  namespace: storesc
  labels:
    app: storesc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storesc-api
  template:
    metadata:
      labels:
        app: storesc-api
    spec:
      containers:
      - name: storesc-api
        image: storesc.azurecr.io/storesc/storesc-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"